version: "3.9"  # optional since v1.27.0

networks:
    backend:

services:
  firebase:
    build:
      context: ../apps/firebase
    container_name: cgw-firebase
    command: firebase emulators:start
    ports:
      - 4000:4000 # Emulator Suite UI
      - 5000:5000 # Firebase Hosting
      - 5001:5001 # Clound Functions
      - 9000:9000 # Realtime Database
      - 8080:8080 # Cloud Firestore
      - 8085:8085 # Cloud Pub/Sub
    volumes:
      - ../apps/firebase:/project
      - ../apps/firebase/bin/:/root/.cache:cached
      - ../apps/firebase/config/:/root/.config:cached
    networks:
        - backend
